site_name: pod
site_description: prueba tecnica
repo_url: https://github.com/LopsanAMO/pod
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/LopsanAMO">LopsanAMO</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Clientes: 'api/clients.md'
    - Grupos: 'api/groups.md'
    - Cuentas: 'api/accounts.md'
    - Transacciones: 'api/transactions.md'
