# Generated by Django 3.0.6 on 2020-05-09 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCalendar',
            fields=[
                ('id', models.IntegerField(default=97147995032, editable=False, primary_key=True, serialize=False)),
                ('num_payment', models.CharField(db_column='num_pago', max_length=50)),
                ('amount', models.CharField(db_column='monto', max_length=50)),
                ('payment_date', models.DateTimeField(db_column='fecha_pago')),
                ('status', models.CharField(db_column='estatus', max_length=50)),
                ('account', models.ForeignKey(db_column='cuenta_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'db_table': 'CalendarioPagos',
            },
        ),
    ]
