# Generated by Django 3.0.6 on 2020-05-10 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(default=26401167708, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='fecha')),
                ('amount', models.CharField(db_column='monto', max_length=50)),
                ('account', models.ForeignKey(db_column='cuenta_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'db_table': 'Transacciones',
            },
        ),
    ]
