# Generated by Django 3.0.6 on 2020-05-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200511_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.CharField(editable=False, max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_column='nombre', max_length=20, unique=True),
        ),
    ]
