# Generated by Django 3.0.6 on 2020-05-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(default='876AC', editable=False, max_length=5, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ini', 'DESEMBOLSADA'), ('fin', 'CERRADA')], db_column='status', default='ini', max_length=50)),
                ('amount', models.DecimalField(db_column='monto', decimal_places=2, max_digits=15)),
                ('balance', models.DecimalField(db_column='saldo', decimal_places=2, max_digits=15)),
                ('num_payments', models.IntegerField(db_column='num_pagos', default=4)),
            ],
            options={
                'db_table': 'Cuentas',
            },
        ),
    ]
