# Generated by Django 3.0.6 on 2020-05-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(default='32CC9', editable=False, max_length=5, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DES', 'DESEMBOLSADA'), ('CER', 'CERRADA')], db_column='status', max_length=50)),
                ('amount', models.DecimalField(db_column='monto', decimal_places=2, max_digits=15)),
                ('balance', models.DecimalField(db_column='saldo', decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'Cuentas',
            },
        ),
    ]
