# Generated by Django 3.0.6 on 2020-05-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(default='15F9E', editable=False, max_length=5, primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='status', max_length=50)),
                ('amount', models.CharField(db_column='monto', max_length=50)),
                ('balance', models.CharField(db_column='saldo', max_length=50)),
            ],
            options={
                'db_table': 'Cuentas',
            },
        ),
    ]
