# Generated by Django 3.0.6 on 2020-05-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
